import React from 'react'

const Terms = () => {
  return (
    <div>
      <h3>Terms and Conditoions</h3>
      <pre>
    
    1.     These Terms of Service ("Terms") regulate your use of and access to the sites and services (together, the "Services") operated and provided by Last List, LLC (together with its officers, directors, employees, agents, subsidiaries and affiliates, “Last List”). Last List’s Privacy Policy explains what personal information Last List collect and how it’s used and shared, and Last List’s Acceptable Use Policy outlines some of your responsibilities when using the Services.
2.     By using or accessing the Services, you agree to these Terms, to Last List’s Privacy Policy and to Last List’s Acceptable Use Policy (together, this “Agreement”). If you do not agree, then you may not use or access the Services.
3.     You must first create an account (“Account”) before you can use the Services. You warrant that the information that you provide us when you open your Account shall be complete and correct and that you shall safeguard your Account and its password and not allow anyone else access to it. You must immediately let us know if you think someone else may have accessed your account. Any activity on your Account is your responsibility entirely and Last List is not liable for any acts or omissions by you in connection with your Account.
4.     No children under the age of 18 may use the Services. By opening an Account, you warrant that you are at least 18.
5.     Last List’s Services depend on the content that you provide and, even though you don’t give us any ownership of that content, you license and authorise us (worldwide, perpetually, royalty-free, sublicensably and transferably) to use it for the limited purpose of the provision, improvement, promotion and protection of the Services.
6.     Whenever you upload, write or publish any content (“Your Content”) on Last List, you warrant to Last List that you own all rights in and/or associated to it and/or have (and shall continue to enjoy) all rights and permissions to use Your Content in the manner contemplated by, and for receipt of, the Services.  You warrant that Last List using Your Content for the Services shall not infringe or violate the rights of any third-party, including, without limitation, any copyrights, trademarks, privacy rights, publicity rights, contract rights or any other intellectual property or proprietary rights.
7.     Content included in the Services, including Your Content may include content that: (a) that is offensive or objectionable; (b) that contains errors; (c) that violates intellectual property, privacy, publicity or other rights of third parties; (d) that is harmful to your computer or network; or (e) the downloading, copying or use of which is subject to additional terms and policies. By operating the Services, Last List does not warrant or imply that Last List endorses Your Content, or that Last List believe such Your Content to be accurate, useful or non-harmful. Last List is not a publisher of, and Last List is not liable for, any content, including Your Content, uploaded, posted, published or otherwise made available using the Services.
8.     The Services let you share Your Content with others, including, without limitation, via those third parties you designate as your guardians (“Your Guardians”). Last List is not responsible for what you share using the Services. You expressly give Last List permission to share Your Content with Your Guardians for the purpose of the Services. You may not attach any conditions to that permission. Last List has no duties to, or in relation to, Your Guardians whatsoever, including, without limitation, to ensure that all or any of them are willing to act as Your Guardians, the correctness of their contact information, their contactability, their reliability, their following of, or adherence to your wishes and/or their willingness or capacity to participate in the Services.  What happens between you and Your Guardians is not at all Last List’s responsibility.
9.     You are responsible for your conduct and Your Content and that of Your Guardians, and you must comply with Last List’s Acceptable Use Policy and make sure that Your Guardians do so. Last List may, but has not obligation to, review your conduct and Your Content for compliance with these Terms and Last List’s Acceptable Use Policy.
10.  You warrant that your use of the Services is not contrary to law, including, without limitation, US export controls, regulations and sanctions.
11.  If and to the extent that any aspect of the Services are integrated with any third-party services, applications and/or sites (together, “Third-Party Services”) that may make available to you their content and/or products and/or services, then you must comply with the terms and policies applicable to the Third-Party. Last List does not control Third-Party Services, and Last List is not liable for Third-Party Services or for any transaction you may enter into with them. Your security when using Third-Party Services is your responsibility. Last List may, at any time and in Last List’s sole discretion, and without any notice to you, suspend, disable access to or remove any Third-Party Services. Last List is not liable to you for any such suspension, disabling or removal, including, without limitation, for any loss of profits, revenue, data, goodwill or other intangible losses you may experience as a result thereof (except where prohibited by law).
12.  The Services may contain links to third-party sites. When you access third-party sites, you do so at your own risk. Last List does not control and is not liable for those sites.
13.  The Services are protected by copyright, trademark and other US and foreign laws. These Terms do not grant you any right, title or interest in the Services, Last List’s trademarks, logos or other brand features or intellectual property, or others’ content in the Services. You agree not to change, translate or otherwise create derivative works of the Services.
14.  Last List welcome your feedback, ideas or suggestions (“Comments”), but you agree that Last List may use your Comments without any restriction or obligation to you, even after this Agreement is terminated.
15.  Last List may provide templates or other products featuring demo content including, without limitation, text, photos, images, graphics, audio, video and other materials (“Demo Content”), to provide you with ideas or inspiration. However, Demo Content is for private use only. You agree that you shall not distribute, publicly display, publicly perform or otherwise publish any Demo Content (or any portion thereof).
16.  Last List reserve these rights, which Last List may exercise at any time and in Last List’s sole discretion, and without liability or notice to you (except where prohibited by law): (a) Last List may change the Services and their functionality; (b) Last List may restrict access to or use of parts or all of the Services; (c) Last List may suspend or discontinue parts or all of the Services; (d) Last List may terminate, suspend or restrict your access to or use of parts or all of the Services; (e) Last List may terminate, suspend or restrict access to your Account or Your Content; and (f) Last List may change Last List’s eligibility criteria to use the Services (and if such eligibility criteria changes are prohibited by law where you live, Last List may revoke your right to use the Services in that jurisdiction).
17.  If there is a dispute about owns or is authorised to have access to an Account or any of Your Content and Last List can’t reasonably determine the rightful owner, Last List is entitled to suspend an Account or site until the disputing parties reach a resolution. Last List also may request documentation, such as a government-issued photo ID, a credit card invoice or a business license, to help determine the rightful owner.
18.  Last List may offer HTTPS encryption for Your Account and/or Your Content. By using the Services, you authorize us to create and maintain a certificate for the limited purpose of providing HTTPS for Your Account and/or Your Content.
19.  Last List’s Privacy Policy explains how Last List handle your and your site visitors’ information. Be sure to read it carefully, as it’s part of Last List’s agreement.
20.  Last List’s Privacy Policy explains how Last List collect, use and share your information.
21.  Last List complies with copyright law, and respond to complaints about copyright infringement in accordance with Last List’s Copyright Policy.
22.  Last List responds to notices of alleged copyright infringement if they comply with the law, and such notices should be reported via the process described in Last List’s Copyright Policy, which is incorporated by reference into this Agreement. Last List is entitled to delete content alleged to be infringing, and to terminate Accounts of infringers without any refunds.
23.  You pay a fee to use the Services. Last List shall tell you about fees for Services before charging you.. If you do not pay for Services, Last List is entitled not to provide you with any Services and/or to suspend or cancel your access to the Services.
24.  All fees are exclusive of applicable federal, state, local or other taxes (“Taxes”). You are responsible for all applicable Taxes, and Last List shall charge Taxes in addition to the fees for the Services when required to do so.
25.  While you or Last List may cancel any Services at any time, you won't be issued a refund except in Last List’s sole discretion, or if legally required.
26.  If you contact your bank or credit card company to decline, chargeback or otherwise reverse the charge of any payable fees to us (“Chargeback”), Last List may automatically terminate your Account.
27.  Last List use third-party payment processors (the “Payment Processors”) to bill you through a payment account linked to your Account. The processing of payments shall be subject to the terms, conditions and privacy policies of the Payment Processors, in addition to this Agreement. Last List does not control and are not liable for the security or performance of the Payment Processors. Last List is entitled to correct, or to instruct Last List’s Payment Processors to correct, any errors or mistakes, even if payment has already been requested or received.
28.  Either of us can end this Agreement at any time.
29.  This Agreement shall remain in effect until terminated by either you or us. To terminate this Agreement, you may Last List to do so. Last List is entitled to suspend or terminate the Services at any time at Last List’s sole discretion and without notice. For example, Last List may suspend or terminate your use of the Services if you are violating these Terms or Last List’s Acceptable Use Policy. All sections of this Agreement that by their nature should survive termination shall survive termination, including, without limitation, Your Content, Last List’s Intellectual Property, Warranty Disclaimers, Limitation Of Liability, Indemnification, Dispute Resolution and Additional Terms.
30.  To the fullest extent permitted by law:
  a.     Last List makes no warranty that the Services shall: (a) be timely, uninterrupted or error-free; (b) meet your requirements or expectations; or (c) be free from viruses or other harmful components. Some places do not allow the disclaimers in this paragraph, so they may not apply to you., Last List makes no warranties, either express or implied, about the Services. The Services are provided “as is.” Last List also disclaims any warranties of merchantability, fitness for a particular purpose and non-infringement. No advice or information, whether oral or written, obtained by you from Last List shall create any warranty;
  b.     In no event shall Last List be liable with respect to any claims arising out of or related to the Services or this Agreement for: (a) any indirect, special, incidental, exemplary, punitive or consequential damages; (b) any loss of profits, revenue, data, goodwill or other intangible losses; (c) any damages related to your access to, use of or inability to access or use the Services or any portion thereof, including, without limitation, interruption of use or cessation or modification of any aspect of the Services; (d) any damages related to loss or corruption of any content or data; (e) any Your Content or other conduct or content of any user or third-party using the Services, including, without limitation, defamatory, offensive or unlawful conduct or content; or (f) any Third-Party Services or third-party sites accessed using the Services. These limitations apply to any theory of liability, whether based on warranty, contract, tort, negligence, strict liability or any other legal theory, whether or not Last List has been informed of the possibility of such damage, and even if a remedy set forth herein is found to have failed its essential purpose. To the fullest extent permitted by law, in no event shall the aggregate liability of Last List for all claims arising out of or related to the Services and this Agreement $10, Some places do not allow the types of limitations in this paragraph, so they may not apply to you; and
  c.     You must indemnify and hold harmless Last List from and against all damages, losses and expenses of any kind (including, without limitation, reasonable attorneys' fees and costs) arising out of or related to: (a) your breach of this Agreement; (b) Your Content; (c) any claims from your End Users; and (d) your violation of any law or regulation or the rights of any third-party.
31.  Either you or Last List may assert claims, if they qualify, in small claims court in New York, New York or any United States county where you live or work. Either you or Last List may bring a lawsuit solely for injunctive relief to stop unauthorized use or abuse of the Services, or intellectual property infringement or misappropriation (for example, trademark, trade secret, copyright or patent rights) without first engaging in arbitration or the informal dispute resolution process described above.
32.  Any judicial proceeding (other than small claims actions) must be brought exclusively in the federal or state courts of New York, New York and you and Last List consent to venue and personal jurisdiction in those courts. Any claim not subject to arbitration must be commenced within one year after the date the party asserting the claim first knows or reasonably should know of the act, omission or default giving rise to the claim. If applicable law prohibits a one year limitation period for asserting claims, any claim must be asserted within the shortest time period permitted by applicable law.
33.  You may only resolve disputes with us on an individual basis, and may not bring a claim as a plaintiff or a class member in a class, consolidated or representative action. Class actions, class arbitrations, private attorney general actions and consolidation with other arbitrations aren't allowed.
34.  This Agreement is the whole agreement between us regarding your use of Last List. If Last List ever change it in a way that materially reduces your rights, Last List shall give you notice and an opportunity to cancel.
35.  This Agreement constitutes the entire agreement between you and Last List regarding the subject matter of this Agreement, and supersedes and replaces any other prior or contemporaneous agreements, or terms and conditions applicable to the subject matter of this Agreement. This Agreement creates no third-party beneficiary rights.
36.  This Agreement and the Services shall be governed in all respects by the laws of the State of New York, without regard to its conflict of law provisions.
37.  Last List’s failure to enforce any provision of this Agreement is not a waiver of Last List’s right to do so later. If any provision of this Agreement is found unenforceable, the remaining provisions shall remain in full effect and an enforceable term shall be substituted reflecting Last List’s intent as closely as possible. You may not assign any of your rights under this Agreement, and any such attempt shall be void. Last List may assign Last List’s rights under this Agreement to any of Last List’s affiliates or subsidiaries, or to any successor in interest of any business associated with the Services.
38.  Last List may modify this Agreement from time to time, and shall always post the most current version on Last List’s site. By continuing to use or access the Services after any modifications come into effect, you must be bound by the modified Agreement. If you disagree with Last List’s changes, then you should stop using the Services.

  Last updated: September [DATE], 2016
1.     These Terms of Service ("Terms") regulate your use of and access to the sites and services (together, the "Services") operated and provided by Last List, LLC (together with its officers, directors, employees, agents, subsidiaries and affiliates, “Last List”). Last List’s Privacy Policy explains what personal information Last List collect and how it’s used and shared, and Last List’s Acceptable Use Policy outlines some of your responsibilities when using the Services.
2.     By using or accessing the Services, you agree to these Terms, to Last List’s Privacy Policy and to Last List’s Acceptable Use Policy (together, this “Agreement”). If you do not agree, then you may not use or access the Services.
3.     You must first create an account (“Account”) before you can use the Services. You warrant that the information that you provide us when you open your Account shall be complete and correct and that you shall safeguard your Account and its password and not allow anyone else access to it. You must immediately let us know if you think someone else may have accessed your account. Any activity on your Account is your responsibility entirely and Last List is not liable for any acts or omissions by you in connection with your Account.
4.     No children under the age of 18 may use the Services. By opening an Account, you warrant that you are at least 18.
5.     Last List’s Services depend on the content that you provide and, even though you don’t give us any ownership of that content, you license and authorise us (worldwide, perpetually, royalty-free, sublicensably and transferably) to use it for the limited purpose of the provision, improvement, promotion and protection of the Services.
6.     Whenever you upload, write or publish any content (“Your Content”) on Last List, you warrant to Last List that you own all rights in and/or associated to it and/or have (and shall continue to enjoy) all rights and permissions to use Your Content in the manner contemplated by, and for receipt of, the Services.  You warrant that Last List using Your Content for the Services shall not infringe or violate the rights of any third-party, including, without limitation, any copyrights, trademarks, privacy rights, publicity rights, contract rights or any other intellectual property or proprietary rights.
7.     Content included in the Services, including Your Content may include content that: (a) that is offensive or objectionable; (b) that contains errors; (c) that violates intellectual property, privacy, publicity or other rights of third parties; (d) that is harmful to your computer or network; or (e) the downloading, copying or use of which is subject to additional terms and policies. By operating the Services, Last List does not warrant or imply that Last List endorses Your Content, or that Last List believe such Your Content to be accurate, useful or non-harmful. Last List is not a publisher of, and Last List is not liable for, any content, including Your Content, uploaded, posted, published or otherwise made available using the Services.
8.     The Services let you share Your Content with others, including, without limitation, via those third parties you designate as your guardians (“Your Guardians”). Last List is not responsible for what you share using the Services. You expressly give Last List permission to share Your Content with Your Guardians for the purpose of the Services. You may not attach any conditions to that permission. Last List has no duties to, or in relation to, Your Guardians whatsoever, including, without limitation, to ensure that all or any of them are willing to act as Your Guardians, the correctness of their contact information, their contactability, their reliability, their following of, or adherence to your wishes and/or their willingness or capacity to participate in the Services.  What happens between you and Your Guardians is not at all Last List’s responsibility.
9.     You are responsible for your conduct and Your Content and that of Your Guardians, and you must comply with Last List’s Acceptable Use Policy and make sure that Your Guardians do so. Last List may, but has not obligation to, review your conduct and Your Content for compliance with these Terms and Last List’s Acceptable Use Policy.
10.  You warrant that your use of the Services is not contrary to law, including, without limitation, US export controls, regulations and sanctions.
11.  If and to the extent that any aspect of the Services are integrated with any third-party services, applications and/or sites (together, “Third-Party Services”) that may make available to you their content and/or products and/or services, then you must comply with the terms and policies applicable to the Third-Party. Last List does not control Third-Party Services, and Last List is not liable for Third-Party Services or for any transaction you may enter into with them. Your security when using Third-Party Services is your responsibility. Last List may, at any time and in Last List’s sole discretion, and without any notice to you, suspend, disable access to or remove any Third-Party Services. Last List is not liable to you for any such suspension, disabling or removal, including, without limitation, for any loss of profits, revenue, data, goodwill or other intangible losses you may experience as a result thereof (except where prohibited by law).
12.  The Services may contain links to third-party sites. When you access third-party sites, you do so at your own risk. Last List does not control and is not liable for those sites.
13.  The Services are protected by copyright, trademark and other US and foreign laws. These Terms do not grant you any right, title or interest in the Services, Last List’s trademarks, logos or other brand features or intellectual property, or others’ content in the Services. You agree not to change, translate or otherwise create derivative works of the Services.
14.  Last List welcome your feedback, ideas or suggestions (“Comments”), but you agree that Last List may use your Comments without any restriction or obligation to you, even after this Agreement is terminated.
15.  Last List may provide templates or other products featuring demo content including, without limitation, text, photos, images, graphics, audio, video and other materials (“Demo Content”), to provide you with ideas or inspiration. However, Demo Content is for private use only. You agree that you shall not distribute, publicly display, publicly perform or otherwise publish any Demo Content (or any portion thereof).
16.  Last List reserve these rights, which Last List may exercise at any time and in Last List’s sole discretion, and without liability or notice to you (except where prohibited by law): (a) Last List may change the Services and their functionality; (b) Last List may restrict access to or use of parts or all of the Services; (c) Last List may suspend or discontinue parts or all of the Services; (d) Last List may terminate, suspend or restrict your access to or use of parts or all of the Services; (e) Last List may terminate, suspend or restrict access to your Account or Your Content; and (f) Last List may change Last List’s eligibility criteria to use the Services (and if such eligibility criteria changes are prohibited by law where you live, Last List may revoke your right to use the Services in that jurisdiction).
17.  If there is a dispute about owns or is authorised to have access to an Account or any of Your Content and Last List can’t reasonably determine the rightful owner, Last List is entitled to suspend an Account or site until the disputing parties reach a resolution. Last List also may request documentation, such as a government-issued photo ID, a credit card invoice or a business license, to help determine the rightful owner.
18.  Last List may offer HTTPS encryption for Your Account and/or Your Content. By using the Services, you authorize us to create and maintain a certificate for the limited purpose of providing HTTPS for Your Account and/or Your Content.
19.  Last List’s Privacy Policy explains how Last List handle your and your site visitors’ information. Be sure to read it carefully, as it’s part of Last List’s agreement.
20.  Last List’s Privacy Policy explains how Last List collect, use and share your information.
21.  Last List complies with copyright law, and respond to complaints about copyright infringement in accordance with Last List’s Copyright Policy.
22.  Last List responds to notices of alleged copyright infringement if they comply with the law, and such notices should be reported via the process described in Last List’s Copyright Policy, which is incorporated by reference into this Agreement. Last List is entitled to delete content alleged to be infringing, and to terminate Accounts of infringers without any refunds.
23.  You pay a fee to use the Services. Last List shall tell you about fees for Services before charging you.. If you do not pay for Services, Last List is entitled not to provide you with any Services and/or to suspend or cancel your access to the Services.
24.  All fees are exclusive of applicable federal, state, local or other taxes (“Taxes”). You are responsible for all applicable Taxes, and Last List shall charge Taxes in addition to the fees for the Services when required to do so.
25.  While you or Last List may cancel any Services at any time, you won't be issued a refund except in Last List’s sole discretion, or if legally required.
26.  If you contact your bank or credit card company to decline, chargeback or otherwise reverse the charge of any payable fees to us (“Chargeback”), Last List may automatically terminate your Account.
27.  Last List use third-party payment processors (the “Payment Processors”) to bill you through a payment account linked to your Account. The processing of payments shall be subject to the terms, conditions and privacy policies of the Payment Processors, in addition to this Agreement. Last List does not control and are not liable for the security or performance of the Payment Processors. Last List is entitled to correct, or to instruct Last List’s Payment Processors to correct, any errors or mistakes, even if payment has already been requested or received.
28.  Either of us can end this Agreement at any time.
29.  This Agreement shall remain in effect until terminated by either you or us. To terminate this Agreement, you may Last List to do so. Last List is entitled to suspend or terminate the Services at any time at Last List’s sole discretion and without notice. For example, Last List may suspend or terminate your use of the Services if you are violating these Terms or Last List’s Acceptable Use Policy. All sections of this Agreement that by their nature should survive termination shall survive termination, including, without limitation, Your Content, Last List’s Intellectual Property, Warranty Disclaimers, Limitation Of Liability, Indemnification, Dispute Resolution and Additional Terms.
30.  To the fullest extent permitted by law:
   a.     Last List makes no warranty that the Services shall: (a) be timely, uninterrupted or error-free; (b) meet your requirements or expectations; or (c) be free from viruses or other harmful components. Some places do not allow the disclaimers in this paragraph, so they may not apply to you., Last List makes no warranties, either express or implied, about the Services. The Services are provided “as is.” Last List also disclaims any warranties of merchantability, fitness for a particular purpose and non-infringement. No advice or information, whether oral or written, obtained by you from Last List shall create any warranty;
   b.     In no event shall Last List be liable with respect to any claims arising out of or related to the Services or this Agreement for: (a) any indirect, special, incidental, exemplary, punitive or consequential damages; (b) any loss of profits, revenue, data, goodwill or other intangible losses; (c) any damages related to your access to, use of or inability to access or use the Services or any portion thereof, including, without limitation, interruption of use or cessation or modification of any aspect of the Services; (d) any damages related to loss or corruption of any content or data; (e) any Your Content or other conduct or content of any user or third-party using the Services, including, without limitation, defamatory, offensive or unlawful conduct or content; or (f) any Third-Party Services or third-party sites accessed using the Services. These limitations apply to any theory of liability, whether based on warranty, contract, tort, negligence, strict liability or any other legal theory, whether or not Last List has been informed of the possibility of such damage, and even if a remedy set forth herein is found to have failed its essential purpose. To the fullest extent permitted by law, in no event shall the aggregate liability of Last List for all claims arising out of or related to the Services and this Agreement $10, Some places do not allow the types of limitations in this paragraph, so they may not apply to you; and
   c.     You must indemnify and hold harmless Last List from and against all damages, losses and expenses of any kind (including, without limitation, reasonable attorneys' fees and costs) arising out of or related to: (a) your breach of this Agreement; (b) Your Content; (c) any claims from your End Users; and (d) your violation of any law or regulation or the rights of any third-party.
31.  Either you or Last List may assert claims, if they qualify, in small claims court in New York, New York or any United States county where you live or work. Either you or Last List may bring a lawsuit solely for injunctive relief to stop unauthorized use or abuse of the Services, or intellectual property infringement or misappropriation (for example, trademark, trade secret, copyright or patent rights) without first engaging in arbitration or the informal dispute resolution process described above.
32.  Any judicial proceeding (other than small claims actions) must be brought exclusively in the federal or state courts of New York, New York and you and Last List consent to venue and personal jurisdiction in those courts. Any claim not subject to arbitration must be commenced within one year after the date the party asserting the claim first knows or reasonably should know of the act, omission or default giving rise to the claim. If applicable law prohibits a one year limitation period for asserting claims, any claim must be asserted within the shortest time period permitted by applicable law.
33.  You may only resolve disputes with us on an individual basis, and may not bring a claim as a plaintiff or a class member in a class, consolidated or representative action. Class actions, class arbitrations, private attorney general actions and consolidation with other arbitrations aren't allowed.
34.  This Agreement is the whole agreement between us regarding your use of Last List. If Last List ever change it in a way that materially reduces your rights, Last List shall give you notice and an opportunity to cancel.
35.  This Agreement constitutes the entire agreement between you and Last List regarding the subject matter of this Agreement, and supersedes and replaces any other prior or contemporaneous agreements, or terms and conditions applicable to the subject matter of this Agreement. This Agreement creates no third-party beneficiary rights.
36.  This Agreement and the Services shall be governed in all respects by the laws of the State of New York, without regard to its conflict of law provisions.
37.  Last List’s failure to enforce any provision of this Agreement is not a waiver of Last List’s right to do so later. If any provision of this Agreement is found unenforceable, the remaining provisions shall remain in full effect and an enforceable term shall be substituted reflecting Last List’s intent as closely as possible. You may not assign any of your rights under this Agreement, and any such attempt shall be void. Last List may assign Last List’s rights under this Agreement to any of Last List’s affiliates or subsidiaries, or to any successor in interest of any business associated with the Services.
38.  Last List may modify this Agreement from time to time, and shall always post the most current version on Last List’s site. By continuing to use or access the Services after any modifications come into effect, you must be bound by the modified Agreement. If you disagree with Last List’s changes, then you should stop using the Services.

    
      </pre>
    </div>
  )
}

export default Terms
